/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kafka;

public class App {

    public static void main(String[] args) {
        String bootstrapServer = "localhost:9092";
        String topic = "mytest";
        String key = "k";
        Producer producer = new Producer(bootstrapServer);
        for(int i = 0; i < 10; i++){
            producer.send(topic, key, Integer.toString(i));
        }

        Consumer consumer = new Consumer(bootstrapServer);
        consumer.subscribe(topic);
        consumer.consumeAndPrint();
    }
}
